[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  SITE_NAME_HEADER = "Latent Bodies"
  SITE_BASE_URL = "https://fabulous-truffle-36a33f.netlify.app"
  dgShowFileTree = "true"
  dgEnableSearch = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

